using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PlatypusTools.UI.Services
{
    /// <summary>
    /// Service for exporting operation results and generating reports.
    /// </summary>
    public class ExportService
    {
        private static readonly Lazy<ExportService> _instance = new(() => new ExportService());
        public static ExportService Instance => _instance.Value;
        
        private ExportService() { }
        
        /// <summary>
        /// Exports data to CSV format.
        /// </summary>
        public async Task ExportToCsvAsync<T>(string filePath, IEnumerable<T> data, 
            Func<T, Dictionary<string, string>>? rowMapper = null)
        {
            var items = data.ToList();
            if (items.Count == 0) return;
            
            var sb = new StringBuilder();
            
            // Get headers from first item
            Dictionary<string, string> firstRow;
            if (rowMapper != null)
            {
                firstRow = rowMapper(items[0]);
            }
            else
            {
                firstRow = GetPropertiesAsDictionary(items[0]);
            }
            
            // Write headers
            sb.AppendLine(string.Join(",", firstRow.Keys.Select(EscapeCsv)));
            
            // Write data rows
            foreach (var item in items)
            {
                var row = rowMapper != null ? rowMapper(item) : GetPropertiesAsDictionary(item);
                sb.AppendLine(string.Join(",", row.Values.Select(EscapeCsv)));
            }
            
            await File.WriteAllTextAsync(filePath, sb.ToString());
        }
        
        /// <summary>
        /// Exports data to HTML format.
        /// </summary>
        public async Task ExportToHtmlAsync<T>(string filePath, IEnumerable<T> data,
            string title = "Export Report", Func<T, Dictionary<string, string>>? rowMapper = null)
        {
            var items = data.ToList();
            if (items.Count == 0) return;
            
            var sb = new StringBuilder();
            
            // HTML Header
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html><head>");
            sb.AppendLine($"<title>{EscapeHtml(title)}</title>");
            sb.AppendLine("<style>");
            sb.AppendLine("body { font-family: 'Segoe UI', Arial, sans-serif; margin: 20px; background: #f5f5f5; }");
            sb.AppendLine("h1 { color: #007ACC; }");
            sb.AppendLine("table { border-collapse: collapse; width: 100%; background: white; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }");
            sb.AppendLine("th { background: #007ACC; color: white; padding: 12px; text-align: left; }");
            sb.AppendLine("td { padding: 10px 12px; border-bottom: 1px solid #eee; }");
            sb.AppendLine("tr:hover { background: #f0f8ff; }");
            sb.AppendLine(".footer { margin-top: 20px; color: #666; font-size: 12px; }");
            sb.AppendLine("</style></head><body>");
            
            sb.AppendLine($"<h1>{EscapeHtml(title)}</h1>");
            sb.AppendLine($"<p>Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}</p>");
            sb.AppendLine($"<p>Total items: {items.Count}</p>");
            
            // Table
            sb.AppendLine("<table>");
            
            // Headers
            var firstRow = rowMapper != null ? rowMapper(items[0]) : GetPropertiesAsDictionary(items[0]);
            sb.AppendLine("<thead><tr>");
            foreach (var header in firstRow.Keys)
            {
                sb.AppendLine($"<th>{EscapeHtml(header)}</th>");
            }
            sb.AppendLine("</tr></thead>");
            
            // Data
            sb.AppendLine("<tbody>");
            foreach (var item in items)
            {
                var row = rowMapper != null ? rowMapper(item) : GetPropertiesAsDictionary(item);
                sb.AppendLine("<tr>");
                foreach (var value in row.Values)
                {
                    sb.AppendLine($"<td>{EscapeHtml(value)}</td>");
                }
                sb.AppendLine("</tr>");
            }
            sb.AppendLine("</tbody></table>");
            
            sb.AppendLine("<div class='footer'>Generated by PlatypusTools</div>");
            sb.AppendLine("</body></html>");
            
            await File.WriteAllTextAsync(filePath, sb.ToString());
        }
        
        /// <summary>
        /// Exports data to JSON format.
        /// </summary>
        public async Task ExportToJsonAsync<T>(string filePath, IEnumerable<T> data)
        {
            var options = new System.Text.Json.JsonSerializerOptions { WriteIndented = true };
            var json = System.Text.Json.JsonSerializer.Serialize(data, options);
            await File.WriteAllTextAsync(filePath, json);
        }
        
        /// <summary>
        /// Exports data to plain text format.
        /// </summary>
        public async Task ExportToTextAsync<T>(string filePath, IEnumerable<T> data,
            string title = "Export Report", Func<T, string>? lineFormatter = null)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine(new string('=', 60));
            sb.AppendLine(title);
            sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine(new string('=', 60));
            sb.AppendLine();
            
            int count = 0;
            foreach (var item in data)
            {
                count++;
                if (lineFormatter != null)
                {
                    sb.AppendLine(lineFormatter(item));
                }
                else
                {
                    sb.AppendLine(item?.ToString() ?? "");
                }
            }
            
            sb.AppendLine();
            sb.AppendLine(new string('-', 60));
            sb.AppendLine($"Total items: {count}");
            
            await File.WriteAllTextAsync(filePath, sb.ToString());
        }
        
        /// <summary>
        /// Generates a file operation report.
        /// </summary>
        public async Task GenerateOperationReportAsync(string filePath, BatchResult result)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine($"# {result.OperationType} Report");
            sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("## Summary");
            sb.AppendLine($"- Total items: {result.TotalItems}");
            sb.AppendLine($"- Successful: {result.SuccessCount}");
            sb.AppendLine($"- Failed: {result.FailedCount}");
            sb.AppendLine($"- Skipped: {result.SkippedCount}");
            if (result.WasCancelled)
            {
                sb.AppendLine($"- **Operation was cancelled**");
            }
            sb.AppendLine();
            
            if (result.ProcessedFiles.Any(f => f.Success))
            {
                sb.AppendLine("## Successful Operations");
                foreach (var file in result.ProcessedFiles.Where(f => f.Success))
                {
                    if (!string.IsNullOrEmpty(file.NewPath))
                    {
                        sb.AppendLine($"- {file.OriginalPath} → {file.NewPath}");
                    }
                    else
                    {
                        sb.AppendLine($"- {file.OriginalPath}");
                    }
                }
                sb.AppendLine();
            }
            
            if (result.ProcessedFiles.Any(f => !f.Success))
            {
                sb.AppendLine("## Failed Operations");
                foreach (var file in result.ProcessedFiles.Where(f => !f.Success))
                {
                    sb.AppendLine($"- {file.OriginalPath}");
                    sb.AppendLine($"  Error: {file.Error}");
                }
            }
            
            await File.WriteAllTextAsync(filePath, sb.ToString());
        }
        
        /// <summary>
        /// Generates a scan summary report.
        /// </summary>
        public async Task GenerateScanReportAsync(string filePath, ScanSummary summary)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine($"# File Scan Report");
            sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();
            sb.AppendLine("## Overview");
            sb.AppendLine($"- Scanned folder: {summary.RootPath}");
            sb.AppendLine($"- Total files: {summary.TotalFiles}");
            sb.AppendLine($"- Total folders: {summary.TotalFolders}");
            sb.AppendLine($"- Total size: {FormatFileSize(summary.TotalSize)}");
            sb.AppendLine($"- Scan duration: {summary.Duration.TotalSeconds:F1} seconds");
            sb.AppendLine();
            
            if (summary.FilesByExtension.Any())
            {
                sb.AppendLine("## Files by Extension");
                foreach (var kv in summary.FilesByExtension.OrderByDescending(x => x.Value))
                {
                    sb.AppendLine($"- {(string.IsNullOrEmpty(kv.Key) ? "(no extension)" : kv.Key)}: {kv.Value} files");
                }
                sb.AppendLine();
            }
            
            if (summary.LargestFiles.Any())
            {
                sb.AppendLine("## Largest Files");
                foreach (var file in summary.LargestFiles.Take(10))
                {
                    sb.AppendLine($"- {file.Path} ({FormatFileSize(file.Size)})");
                }
            }
            
            await File.WriteAllTextAsync(filePath, sb.ToString());
        }
        
        private Dictionary<string, string> GetPropertiesAsDictionary<T>(T obj)
        {
            var dict = new Dictionary<string, string>();
            if (obj == null) return dict;
            
            foreach (var prop in typeof(T).GetProperties())
            {
                try
                {
                    var value = prop.GetValue(obj);
                    dict[prop.Name] = value?.ToString() ?? "";
                }
                catch { }
            }
            return dict;
        }
        
        private string EscapeCsv(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            if (value.Contains(',') || value.Contains('"') || value.Contains('\n'))
            {
                return $"\"{value.Replace("\"", "\"\"")}\"";
            }
            return value;
        }
        
        private string EscapeHtml(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            return value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
        }
        
        private string FormatFileSize(long bytes)
        {
            if (bytes < 1024) return $"{bytes} B";
            if (bytes < 1024 * 1024) return $"{bytes / 1024.0:F1} KB";
            if (bytes < 1024 * 1024 * 1024) return $"{bytes / (1024.0 * 1024.0):F1} MB";
            return $"{bytes / (1024.0 * 1024.0 * 1024.0):F2} GB";
        }
    }
    
    public class ScanSummary
    {
        public string RootPath { get; set; } = "";
        public int TotalFiles { get; set; }
        public int TotalFolders { get; set; }
        public long TotalSize { get; set; }
        public TimeSpan Duration { get; set; }
        public Dictionary<string, int> FilesByExtension { get; set; } = new();
        public List<FileEntry> LargestFiles { get; set; } = new();
        public List<FileEntry> OldestFiles { get; set; } = new();
        public List<FileEntry> NewestFiles { get; set; } = new();
    }
    
    public class FileEntry
    {
        public string Path { get; set; } = "";
        public long Size { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
    }
}
