Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# ---------- Helper functions ----------
function Get-VideoFiles($path) {
    $exts = @(".mp4", ".mkv", ".avi", ".mov", ".wmv", ".flv", ".webm")
    if (-not (Test-Path $path)) { return @() }
    Get-ChildItem -Path $path -File -Recurse | Where-Object { $exts -contains $_.Extension.ToLower() }
}

function Normalize-Whitespace($s) {
    return ($s -replace '\s{2,}', ' ').Trim()
}

function Strip-AllPrefixAndEpisode($name, $prefixToRemove, $prefixToAdd, $seasonEnabled, $seasonNumber, $epPattern, $seasonPattern) {
    $n = $name
    if (-not [string]::IsNullOrWhiteSpace($prefixToRemove)) {
        $n = $n -replace [Regex]::Escape($prefixToRemove), ''
    }
    if (-not [string]::IsNullOrWhiteSpace($prefixToAdd)) {
        $n = $n -replace [Regex]::Escape($prefixToAdd), ''
    }
    $n = $n -replace $epPattern, ''
    $n = $n -replace $seasonPattern, ''
    return Normalize-Whitespace($n)
}

function Build-NewName($prefixToAdd, $episodeNumber, $baseName, $padding, $seasonEnabled, $seasonNumber) {
    if ([string]::IsNullOrWhiteSpace($prefixToAdd)) { $prefixToAdd = "" }
    if ($seasonEnabled) {
        $seasonTag = "S{0:D2}" -f [int]$seasonNumber
        $epTag = ("E{0:D" + $padding + "}") -f [int]$episodeNumber
        $name = "$prefixToAdd $seasonTag$epTag $baseName"
    } else {
        $epTag = ("E{0:D" + $padding + "}") -f [int]$episodeNumber
        $name = "$prefixToAdd $epTag $baseName"
    }
    return Normalize-Whitespace($name)
}

function Save-BackupAndUndo($backupEntries, $folderPath, $opPrefix) {
    $time = (Get-Date).ToString('yyyyMMdd_HHmmss')
    $backupFile = Join-Path $folderPath ("${opPrefix}_backup_$time.csv")
    $undoScript = Join-Path $folderPath ("undo_${opPrefix}_$time.ps1")
    if ($backupEntries.Count -gt 0) {
        $backupEntries | Export-Csv -Path $backupFile -NoTypeInformation
        $undoLines = @("# Undo script generated by BatchVideoRenamer", "# Run in PowerShell to revert changes")
        foreach ($b in $backupEntries) {
            $orig = $b.OriginalName
            $new = $b.NewName
            $dir = $b.Directory
            $undoLines += "Rename-Item -Path `"" + (Join-Path $dir $new) + "`" -NewName `"" + $orig + "`""
        }
        $undoLines | Set-Content -Path $undoScript -Encoding UTF8
        return @{Backup = $backupFile; Undo = $undoScript}
    } else {
        return $null
    }
}

# ---------- UI setup ----------
$form = New-Object System.Windows.Forms.Form
$form.Text = "Batch Video Renamer"
$form.Size = New-Object Drawing.Size(920, 760)
$form.StartPosition = "CenterScreen"
$form.Font = New-Object Drawing.Font("Segoe UI",9)

# Panels for layout
$topPanel = New-Object System.Windows.Forms.Panel -Property @{ Location = [Drawing.Point]::new(10,10); Size = [Drawing.Size]::new(880,140) }
$middlePanel = New-Object System.Windows.Forms.Panel -Property @{ Location = [Drawing.Point]::new(10,160); Size = [Drawing.Size]::new(880,440) }
$bottomPanel = New-Object System.Windows.Forms.Panel -Property @{ Location = [Drawing.Point]::new(10,610); Size = [Drawing.Size]::new(880,120) }

$form.Controls.AddRange(@($topPanel, $middlePanel, $bottomPanel))

# Top panel controls (folder + prefix inputs + season + padding)
$lblFolder = New-Object System.Windows.Forms.Label -Property @{ Text = "Target Folder"; Location = [Drawing.Point]::new(6,8); AutoSize = $true }
$txtFolder = New-Object System.Windows.Forms.TextBox -Property @{ Location = [Drawing.Point]::new(6,30); Size = [Drawing.Size]::new(660,24) }
$btnBrowse = New-Object System.Windows.Forms.Button -Property @{ Text = "Browse"; Location = [Drawing.Point]::new(678,30); Size = [Drawing.Size]::new(80,24) }
$btnBrowse.Add_Click({
    $d = New-Object System.Windows.Forms.FolderBrowserDialog
    if ($d.ShowDialog() -eq 'OK') { $txtFolder.Text = $d.SelectedPath }
})

$lblRemove = New-Object System.Windows.Forms.Label -Property @{ Text = "Prefix to Remove"; Location = [Drawing.Point]::new(6,64); AutoSize = $true }
$txtRemove = New-Object System.Windows.Forms.TextBox -Property @{ Location = [Drawing.Point]::new(120,60); Size = [Drawing.Size]::new(220,24) }
$lblAdd = New-Object System.Windows.Forms.Label -Property @{ Text = "Prefix to Add"; Location = [Drawing.Point]::new(360,64); AutoSize = $true }
$txtAdd = New-Object System.Windows.Forms.TextBox -Property @{ Location = [Drawing.Point]::new(450,60); Size = [Drawing.Size]::new(220,24) }

# Season controls
$chkSeason = New-Object System.Windows.Forms.CheckBox -Property @{ Text = "Include Season Tag (Sxx)"; Location = [Drawing.Point]::new(6,96); Size = [Drawing.Size]::new(180,22) }
$lblSeasonNum = New-Object System.Windows.Forms.Label -Property @{ Text = "Season #"; Location = [Drawing.Point]::new(196,98); AutoSize = $true }
$numSeason = New-Object System.Windows.Forms.NumericUpDown -Property @{ Location = [Drawing.Point]::new(256,94); Size = [Drawing.Size]::new(60,24); Minimum=0; Maximum=99; Value=1 }

# Padding controls
$lblPadding = New-Object System.Windows.Forms.Label -Property @{ Text = "Episode Padding (digits)"; Location = [Drawing.Point]::new(340,98); AutoSize = $true }
$numPadding = New-Object System.Windows.Forms.NumericUpDown -Property @{ Location = [Drawing.Point]::new(480,94); Size = [Drawing.Size]::new(60,24); Minimum=1; Maximum=6; Value=3 }

# Mode dropdown
$lblMode = New-Object System.Windows.Forms.Label -Property @{ Text = "Mode"; Location = [Drawing.Point]::new(560,98); AutoSize = $true }
$comboMode = New-Object System.Windows.Forms.ComboBox -Property @{ Location = [Drawing.Point]::new(600,94); Size = [Drawing.Size]::new(120,24); DropDownStyle = 'DropDownList' }
$comboMode.Items.AddRange(@("WhatIf","Run")); $comboMode.SelectedIndex = 0

$topPanel.Controls.AddRange(@($lblFolder,$txtFolder,$btnBrowse,$lblRemove,$txtRemove,$lblAdd,$txtAdd,$chkSeason,$lblSeasonNum,$numSeason,$lblPadding,$numPadding,$lblMode,$comboMode))

# Tooltips
$tt = New-Object System.Windows.Forms.ToolTip
$tt.SetToolTip($txtRemove,"Optional: remove this prefix from filenames before building the new name.")
$tt.SetToolTip($txtAdd,"Prefix to add to each file (will appear once). Leave empty to only renumber/clear.")
$tt.SetToolTip($chkSeason,"If checked, names will include S## before E### (S01E001).")
$tt.SetToolTip($numPadding,"Number of digits for episode numbering (e.g., 2 => E01, 3 => E001).")

# Middle panel: left control group and right preview grid
$leftGroup = New-Object System.Windows.Forms.GroupBox -Property @{ Text = "Actions"; Location = [Drawing.Point]::new(6,6); Size = [Drawing.Size]::new(300,420) }
$middlePanel.Controls.Add($leftGroup)

$btnPreviewAll = New-Object System.Windows.Forms.Button -Property @{ Text = "Preview All"; Location = [Drawing.Point]::new(12,28); Size = [Drawing.Size]::new(270,32) }
$btnPreviewRename = New-Object System.Windows.Forms.Button -Property @{ Text = "Preview Rename"; Location = [Drawing.Point]::new(12,68); Size = [Drawing.Size]::new(270,32) }
$btnPreviewForceRename = New-Object System.Windows.Forms.Button -Property @{ Text = "Preview Force Rename"; Location = [Drawing.Point]::new(12,108); Size = [Drawing.Size]::new(270,32) }
$btnPreviewRenumber = New-Object System.Windows.Forms.Button -Property @{ Text = "Preview Renumber"; Location = [Drawing.Point]::new(12,148); Size = [Drawing.Size]::new(270,32) }

$chkForceRename = New-Object System.Windows.Forms.CheckBox -Property @{ Text = "Force Rename (cleanup duplicates)"; Location = [Drawing.Point]::new(12,192); Size = [Drawing.Size]::new(270,22) }
$chkForceRenumber = New-Object System.Windows.Forms.CheckBox -Property @{ Text = "Force Renumber (re-number all alphabetically)"; Location = [Drawing.Point]::new(12,216); Size = [Drawing.Size]::new(270,22) }

$btnRename = New-Object System.Windows.Forms.Button -Property @{ Text = "Run Rename"; Location = [Drawing.Point]::new(12,246); Size = [Drawing.Size]::new(130,36) }
$btnForceRename = New-Object System.Windows.Forms.Button -Property @{ Text = "Run Force Rename"; Location = [Drawing.Point]::new(152,246); Size = [Drawing.Size]::new(130,36) }
$btnRenumber = New-Object System.Windows.Forms.Button -Property @{ Text = "Run Renumber"; Location = [Drawing.Point]::new(12,292); Size = [Drawing.Size]::new(130,36) }
$btnForceRenumber = New-Object System.Windows.Forms.Button -Property @{ Text = "Run Force Renumber"; Location = [Drawing.Point]::new(152,292); Size = [Drawing.Size]::new(130,36) }

$btnExportCSV = New-Object System.Windows.Forms.Button -Property @{ Text = "Export Preview CSV"; Location = [Drawing.Point]::new(12,340); Size = [Drawing.Size]::new(270,34) }
$btnSaveLogs = New-Object System.Windows.Forms.Button -Property @{ Text = "Save Logs"; Location = [Drawing.Point]::new(12,380); Size = [Drawing.Size]::new(130,28) }
$btnExit = New-Object System.Windows.Forms.Button -Property @{ Text = "Exit"; Location = [Drawing.Point]::new(152,380); Size = [Drawing.Size]::new(130,28) }

$leftGroup.Controls.AddRange(@(
    $btnPreviewAll,
    $btnPreviewRename,
    $btnPreviewForceRename,
    $btnPreviewRenumber,
    $chkForceRename,
    $chkForceRenumber,
    $btnRename,
    $btnForceRename,
    $btnRenumber,
    $btnForceRenumber,
    $btnExportCSV,
    $btnSaveLogs,
    $btnExit
))

# Right: preview ListView
$listView = New-Object System.Windows.Forms.ListView -Property @{ View='Details'; FullRowSelect=$true; Location=[Drawing.Point]::new(318,6); Size=[Drawing.Size]::new(554,420); GridLines=$true; MultiSelect=$false }
$listView.Columns.Add("Original",260) | Out-Null
$listView.Columns.Add("Proposed",260) | Out-Null
$middlePanel.Controls.Add($listView)

# Bottom panel: logs, progress, status
$grpLog = New-Object System.Windows.Forms.GroupBox -Property @{ Text = "Log / Status"; Location = [Drawing.Point]::new(6,6); Size = [Drawing.Size]::new(868,104) }
$txtLog = New-Object System.Windows.Forms.TextBox -Property @{ Multiline=$true; ScrollBars='Vertical'; ReadOnly=$true; Location=[Drawing.Point]::new(8,22); Size=[Drawing.Size]::new(720,76) }
$lblStatus = New-Object System.Windows.Forms.Label -Property @{ Text = "Status: Idle"; Location = [Drawing.Point]::new(734,28); AutoSize=$true; ForeColor=[Drawing.Color]::DarkGreen }
$progress = New-Object System.Windows.Forms.ProgressBar -Property @{ Location = [Drawing.Point]::new(734,52); Size = [Drawing.Size]::new(120,46) }

$grpLog.Controls.AddRange(@($txtLog,$lblStatus,$progress))
$bottomPanel.Controls.Add($grpLog)

# ---------- Shared variables ----------
$global:CurrentPreviewPlan = @()
$episodePattern = "E\d{1,6}"
$seasonPattern = "S\d{1,2}"

# ---------- Preview builder (fixed: per-file proposed, "Unchanged" display) ----------
function Build-PreviewPlan([string]$mode) {
    $listView.Items.Clear()
    $txtLog.Clear()
    $progress.Value = 0
    $folder = $txtFolder.Text
    if (-not (Test-Path $folder)) {
        [System.Windows.Forms.MessageBox]::Show("Please choose a valid folder first.","Error",[System.Windows.Forms.MessageBoxButtons]::OK)
        return
    }

    $prefixRemove = $txtRemove.Text
    $prefixAdd = $txtAdd.Text
    $seasonEnabled = $chkSeason.Checked
    $seasonNumber = [int]$numSeason.Value
    $padding = [int]$numPadding.Value
    $forceRename = $chkForceRename.Checked
    $forceRenumber = $chkForceRenumber.Checked

    $files = Get-VideoFiles $folder | Sort-Object Name
    if ($files.Count -eq 0) {
        $txtLog.AppendText("No video files found.`r`n"); return
    }

    $plan = @()
    $ep = 1

    foreach ($f in $files) {
        $orig = $f.Name
        $base = $orig
        $proposed = $null

        switch ($mode) {
            "All" {
                if ($forceRename -or $forceRenumber) {
                    $cleanBase = Strip-AllPrefixAndEpisode $base $prefixRemove $prefixAdd $seasonEnabled $seasonNumber $episodePattern $seasonPattern
                    $proposed = Build-NewName $prefixAdd $ep $cleanBase $padding $seasonEnabled $seasonNumber
                } else {
                    if (($orig.StartsWith($prefixAdd) -and ($orig -match $episodePattern)) -or ($orig -match $seasonPattern)) {
                        $txtLog.AppendText("Keep (already tagged): $orig`r`n")
                        $proposed = $null
                    } else {
                        $cleanBase = Strip-AllPrefixAndEpisode $base $prefixRemove $prefixAdd $seasonEnabled $seasonNumber $episodePattern $seasonPattern
                        $proposed = Build-NewName $prefixAdd $ep $cleanBase $padding $seasonEnabled $seasonNumber
                    }
                }
            }
            "Rename" {
                if (($orig.StartsWith($prefixAdd) -and ($orig -match $episodePattern) -and -not $chkForceRename.Checked) -and (-not $orig -match $seasonPattern -or -not $seasonEnabled)) {
                    $txtLog.AppendText("Keep (already tagged): $orig`r`n")
                    $proposed = $null
                } else {
                    $cleanBase = Strip-AllPrefixAndEpisode $base $prefixRemove $prefixAdd $seasonEnabled $seasonNumber $episodePattern $seasonPattern
                    $proposed = Build-NewName $prefixAdd $ep $cleanBase $padding $seasonEnabled $seasonNumber
                }
            }
            "ForceRename" {
                $cleanBase = Strip-AllPrefixAndEpisode $base $prefixRemove $prefixAdd $seasonEnabled $seasonNumber $episodePattern $seasonPattern
                $proposed = Build-NewName $prefixAdd $ep $cleanBase $padding $seasonEnabled $seasonNumber
            }
            "Renumber" {
                if (($orig.StartsWith($prefixAdd) -and ($orig -match $episodePattern)) -and -not $chkForceRenumber.Checked) {
                    $txtLog.AppendText("Keep (already numbered): $orig`r`n")
                    $proposed = $null
                } else {
                    $temp = $base -replace $episodePattern, ''
                    $temp = $temp -replace [Regex]::Escape($prefixRemove), ''
                    $temp = $temp -replace [Regex]::Escape($prefixAdd), ''
                    $temp = $temp -replace $seasonPattern, ''
                    $temp = Normalize-Whitespace($temp)
                    $proposed = Build-NewName $prefixAdd $ep $temp $padding $seasonEnabled $seasonNumber
                }
            }
            default {
                $cleanBase = Strip-AllPrefixAndEpisode $base $prefixRemove $prefixAdd $seasonEnabled $seasonNumber $episodePattern $seasonPattern
                $proposed = Build-NewName $prefixAdd $ep $cleanBase $padding $seasonEnabled $seasonNumber
            }
        }

        if ([string]::IsNullOrWhiteSpace($proposed) -or ($proposed -ieq $orig)) {
            $itm = New-Object System.Windows.Forms.ListViewItem($orig)
            $itm.SubItems.Add("Unchanged")
            $listView.Items.Add($itm)
        } else {
            $candidate = $proposed
            $destPath = Join-Path $f.DirectoryName $candidate
            if (Test-Path $destPath) {
                $nameOnly = [System.IO.Path]::GetFileNameWithoutExtension($candidate)
                $ext = [System.IO.Path]::GetExtension($candidate)
                $candidate = "$nameOnly-duplicate$ext"
                $txtLog.AppendText("Duplicate proposed name resolved: $candidate`r`n")
            }

            $itm = New-Object System.Windows.Forms.ListViewItem($orig)
            $itm.SubItems.Add($candidate)
            $listView.Items.Add($itm)

            $plan += [PSCustomObject]@{
                File = $f
                OriginalName = $orig
                NewName = $candidate
                Directory = $f.DirectoryName
            }
        }

        $ep++
    }

    $global:CurrentPreviewPlan = $plan
    $txtLog.AppendText("Preview built: {0} items (proposed renames: {1}).`r`n" -f ($files.Count), ($plan.Count))
    $lblStatus.Text = "Status: Preview ready"
    $progress.Value = 100
}

# ---------- Preview button handlers ----------
$btnPreviewAll.Add_Click({ Build-PreviewPlan "All" })
$btnPreviewRename.Add_Click({ Build-PreviewPlan "Rename" })
$btnPreviewForceRename.Add_Click({ Build-PreviewPlan "ForceRename" })
$btnPreviewRenumber.Add_Click({ Build-PreviewPlan "Renumber" })

# ---------- CSV Export of current preview ----------
$btnExportCSV.Add_Click({
    if ($global:CurrentPreviewPlan.Count -eq 0) {
        [System.Windows.Forms.MessageBox]::Show("No preview data to export. Run a preview first.","No Data",[System.Windows.Forms.MessageBoxButtons]::OK)
        return
    }
    $folder = $txtFolder.Text
    if (-not (Test-Path $folder)) {
        [System.Windows.Forms.MessageBox]::Show("Choose a valid folder.","Error",[System.Windows.Forms.MessageBoxButtons]::OK)
        return
    }
    $time = (Get-Date).ToString('yyyyMMdd_HHmmss')
    $csvPath = Join-Path $folder ("preview_plan_$time.csv")
    $export = $global:CurrentPreviewPlan | Select-Object Directory,OriginalName,NewName
    $export | Export-Csv -Path $csvPath -NoTypeInformation
    [System.Windows.Forms.MessageBox]::Show("Preview exported to: $csvPath","Exported",[System.Windows.Forms.MessageBoxButtons]::OK)
    $txtLog.AppendText("Preview exported to: $csvPath`r`n")
})

# ---------- Core perform operation ----------
function Perform-Operation([string]$opName, [switch]$usePreviewPlan) {
    $folder = $txtFolder.Text
    if (-not (Test-Path $folder)) { [System.Windows.Forms.MessageBox]::Show("Choose a valid folder.","Error",[System.Windows.Forms.MessageBoxButtons]::OK); return }
    $mode = $comboMode.SelectedItem
    $plan = @()
    if ($usePreviewPlan.IsPresent -and $global:CurrentPreviewPlan.Count -gt 0) {
        $plan = $global:CurrentPreviewPlan
    } else {
        Build-PreviewPlan $opName
        $plan = $global:CurrentPreviewPlan
    }
    if ($plan.Count -eq 0) { $txtLog.AppendText("Nothing to do.`r`n"); return }

    $txtLog.AppendText("Starting $opName ...`r`n")
    $lblStatus.Text = "Status: Running"
    $progress.Value = 0
    $count = $plan.Count
    $step = [Math]::Max(1, [int](100 / $count))
    $backups = @()

    for ($i = 0; $i -lt $plan.Count; $i++) {
        $entry = $plan[$i]
        $src = $entry.File.FullName
        $dstName = $entry.NewName
        $dstPath = Join-Path $entry.Directory $dstName

        try {
            if ($mode -eq 'Run') {
                if ($entry.OriginalName -ne $dstName) {
                    Rename-Item -Path $src -NewName $dstName -ErrorAction Stop
                    $txtLog.AppendText("Renamed: $($entry.OriginalName) -> $dstName`r`n")
                } else {
                    $txtLog.AppendText("Skipped (already correct): $($entry.OriginalName)`r`n")
                }
            } else {
                $txtLog.AppendText("Simulated: $($entry.OriginalName) -> $dstName`r`n")
            }

            $backups += [PSCustomObject]@{
                OriginalName = $entry.OriginalName
                NewName = $dstName
                Directory = $entry.Directory
            }
        } catch {
            $txtLog.AppendText("Error renaming $($entry.OriginalName): $($_.Exception.Message)`r`n")
        }

        $progress.Value = [Math]::Min($progress.Value + $step, 100)
    }

    $res = Save-BackupAndUndo $backups $folder ($opName.ToLower())
    if ($res) {
        $txtLog.AppendText("Backup: $($res.Backup)`r`nUndo script: $($res.Undo)`r`n")
    }
    $lblStatus.Text = "Status: Complete"
    [System.Windows.Forms.MessageBox]::Show("$opName complete.","Done",[System.Windows.Forms.MessageBoxButtons]::OK)
}

# ---------- Run buttons ----------
$btnRename.Add_Click({ Build-PreviewPlan "Rename"; Perform-Operation "Rename" -usePreviewPlan })
$btnForceRename.Add_Click({
    $chkForceRename.Checked = $true
    Build-PreviewPlan "ForceRename"
    Perform-Operation "ForceRename" -usePreviewPlan
})
$btnRenumber.Add_Click({
    Build-PreviewPlan "Renumber"
    Perform-Operation "Renumber" -usePreviewPlan
})
$btnForceRenumber.Add_Click({
    $chkForceRenumber.Checked = $true
    Build-PreviewPlan "Renumber"
    Perform-Operation "ForceRenumber" -usePreviewPlan
})

# ---------- Safe event handlers, drag & drop, and show form ----------
if ($null -ne $listView) {
    $listView.Add_MouseDoubleClick({
        if ($listView.SelectedItems.Count -gt 0) {
            $si = $listView.SelectedItems[0]
            try {
                [System.Windows.Forms.Clipboard]::SetText($si.SubItems[1].Text)
                $txtLog.AppendText("Copied proposed name to clipboard: " + $si.SubItems[1].Text + "`r`n")
            } catch {
                $txtLog.AppendText("Failed to copy to clipboard: " + $_.Exception.Message + "`r`n")
            }
        }
    })
} else {
    $txtLog.AppendText("Warning: preview list view not available; double-click copy disabled.`r`n")
}

# Drag & drop folder support on form (safe checks)
$form.Add_DragEnter({
    try { $_.Effect = 'Copy' } catch {}
})
$form.Add_DragDrop({
    try {
        $paths = $_.Data.GetData("FileDrop")
        if ($paths -and $paths.Count -gt 0) {
            $first = $paths[0]
            if (Test-Path $first -PathType Container) { $txtFolder.Text = $first }
        }
    } catch {
        $txtLog.AppendText("DragDrop error: " + $_.Exception.Message + "`r`n")
    }
})

# Save logs button (ensure control exists)
if ($null -ne $btnSaveLogs) {
    $btnSaveLogs.Add_Click({
        $folder = $txtFolder.Text
        if (-not (Test-Path $folder)) { [System.Windows.Forms.MessageBox]::Show("Choose a valid folder.","Error",[System.Windows.Forms.MessageBoxButtons]::OK); return }
        $logPath = Join-Path $folder ("batch_renamer_log_" + (Get-Date).ToString('yyyyMMdd_HHmmss') + ".txt")
        $txtLog.Text | Set-Content -Path $logPath -Encoding UTF8
        [System.Windows.Forms.MessageBox]::Show("Log saved to: $logPath","Saved",[System.Windows.Forms.MessageBoxButtons]::OK)
    })
}

# Exit button
if ($null -ne $btnExit) {
    $btnExit.Add_Click({ $form.Close() })
}

# Show the form
[void]$form.ShowDialog()